spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
  datasource:
    username: root
    password: ai1194169073
    url: jdbc:mysql://localhost:3306/skindow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  data:
      mongodb:
        uri: mongodb://localhost:27017/test
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: ../skindow-api/com.skindow.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
server:
  port: 8093
