spring:
 datasource:
    username: root
    password: ai1194169073
    url: jdbc:mysql://localhost:3306/user_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8094
